#! /bin/sh
source config.sh

echo "Please choose the action:(1):commit (2):update (3):commitall (4):updateall (5):exit"

select item in commit  commitall update updateall exit
do
	if [ $item = "commit" ];then
		echo 'backup is processing......'
		echo 'rm -fr '$sqlfile'.zip' $sqlfile
		rm -fr $sqlfile.zip  $sqlfile
		echo 'backup mysql database'
		mysqldump --quick --databases $DBNAME --flush-logs --delete-master-logs --lock-all-tables --default-character-set=utf8 -u $DB_USER -p$mysql_passwd > $sqlfile
		echo 'make zip package '$sqlfile'.zip'
		zip  -u -P $rar_passwd $sqlfile.zip $sqlfile uc_bookmark.sdr config.sh  bm_logo.psd  url2img.exe qsqlmysql4.dll qsqlmysql4.exp qsqlmysql4.lib libmysql.lib libmySQL.dll cap.exe
		rm -f $sqlfile 
		echo 'commit is processing......'
		for svni in $svnfiles
		do
		    echo 'svn commit '$svni
		    svn commit -m  '$logdate' $svni
		done   
	elif [ $item = "commitall" ];then
		echo 'backup is processing......'
		echo 'rm -fr '$sqlfile'.zip' $sqlfile
		rm -fr $sqlfile.zip $sqlfile
		echo 'backup mysql database'
		mysqldump --quick --databases $DBNAME --flush-logs --delete-master-logs --lock-all-tables --default-character-set=utf8 -u $DB_USER -p$mysql_passwd > $sqlfile
		echo 'make zip package '$sqlfile'.zip'
		zip  -u -P $rar_passwd $sqlfile.zip $sqlfile uc_bookmark.sdr config.sh  bm_logo.psd  url2img.exe qsqlmysql4.dll qsqlmysql4.exp qsqlmysql4.lib libmysql.lib libmySQL.dll cap.exe
		rm -f $sqlfile 
		echo 'commit is processing......'
		for svni in $svnallfiles
		do
		    echo 'svn commit '$svni
		    svn commit -m  '$logdate' $svni
		done
		svn add snapshot/*/*/*/*/*
		svn commit  -m  '$logdate'   snapshot/*/*/*/*/*
	elif  [ $item = "update" ];then
		
		echo 'update is processing......'
		for svni in $svnfiles
		do
		    echo 'svn update '$svni
		    svn update $svni
		    chmod -R 777 $svni
		done
		echo 'unzip '$sqlfile'.zip'
		unzip -xo -P $rar_passwd  $sqlfile.zip
		echo 'restore mysql database.......'
		mysql -u $DB_USER -p$mysql_passwd  < $sqlfile

	elif  [ $item = "updateall" ];then
		
		echo 'update is processing......'
		for svni in $svnallfiles
		do
		    echo 'svn update '$svni
		    svn update $svni
		    chmod -R 777 $svni
		done
		echo 'unzip '$sqlfile'.zip'
		unzip -xo -P $rar_passwd  $sqlfile.zip
		echo 'restore mysql database.......'
		mysql -u $DB_USER -p$mysql_passwd  < $sqlfile
	elif [ $item = "exit" ];then
	   break;
	else
	   echo "error!"
	fi
done  
echo "Done !!!"
